services:
  api:
    image: ghcr.io/ponlponl123/geoip-api:main
    build: .
    ports:
      - "4002:4002"
    environment:
      - PORT=4002
      - NODE_ENV=production
      - REDIS_ENABLED=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
